"""Strongest / weakest side per model family."""
import json

V = {
 'Veo 3.1': ("Best-in-class prompt adherence and native dialogue+SFX audio; 4K tier; reference-to-video and first/last-frame variants all share one quality bar.",
             "Only 16:9 and 9:16, hard 8s ceiling, no multi-shot, and the most expensive per-second tier once audio is on. Heavy content filtering rejects many prompts."),
 'Kling 3': ("Native multi-shot (multi_prompt + shot_type) up to 15s with native audio — rare combination. Strong cinematic motion and camera language.",
             "Audio-on roughly doubles cost. No resolution selector on the endpoint; 4K is a separate pricier endpoint."),
 'Kling O3': ("Kling's realism-tuned line: strong physical plausibility, plus reference-to-video and 4K variants. Cheaper than v3 at the standard tier.",
             "Fewer creative/stylized results than v3; audio surcharge; reference fidelity trails Vidu/Seedance on multi-subject scenes."),
 'Kling O1': ("Purpose-built start-frame → end-frame interpolation with text-guided styling; very reliable transitions.",
             "Narrow use case — it is an in-betweener, not a general generator. No audio."),
 'Kling 2.6': ("Cheapest Kling tier with native audio ($0.07/s audio-off). Good quality-per-dollar for social content.",
             "No multi-shot, no explicit resolution control, and audio doubles the price."),
 'Kling 2.5T': ("Excellent motion fluidity and prompt precision at a low flat rate; the value pick in the Kling line.",
                "No audio at all, 5s/10s only, 1:1/16:9/9:16 only."),
 'Kling 2.1': ("Master tier still has the most cinematic look of the older Kling generations; three price tiers (std/pro/master) for the same API shape.",
               "Master is expensive ($1.40/5s), no audio, and superseded by 2.5T/3 on both price and quality."),
 'Kling 2.0': ("Master-grade visuals with simple, stable API; good for period/cinematic looks.",
               "Legacy — no audio, no multi-shot, priced above newer and better tiers."),
 'Kling 1.6': ("Cheap workhorse with an 'elements' mode for multi-subject composition; still fine for simple motion.",
               "Dated visual quality, visible artifacting on fast motion, no audio."),
 'Kling 1.5': ("Pro-tier effects endpoints and dependable image-to-video for simple shots.",
               "Superseded on every axis; no audio, low resolution ceiling."),
 'Kling 1.0': ("Lowest-cost entry into the Kling API surface; effects presets included.",
               "Clearly obsolete quality — soft detail, weak prompt adherence, no audio."),
 'Kling Avatar': ("Audio-driven talking avatars up to 60s that handle humans, animals, cartoons and stylized characters equally well.",
                  "Pro tier costs 2x Standard for modest gains; body motion below the neck is limited; needs a clean single-speaker audio track."),
 'Kling Lipsync': ("Cheap ($0.014/input-second) re-dubbing of an existing video with accurate mouth shapes.",
                   "Edits an existing clip only — it generates nothing. Billing rounds up to 5s increments."),

 'Seedance 2.5': ("Native 30-second single-shot generation with whole-shot reasoning — identity, lighting and motion stay coherent far longer than rivals. Seven aspect ratios.",
                  "By far the priciest per second at 720p (~$0.47/s), and capped at 720p — no 1080p or 4K."),
 'Seedance 2.0': ("Multi-shot editing, native audio, real-world physics and director-level camera control, with fast/mini tiers and reference-to-video across the line.",
                  "720p costs ~$0.30/s; 1080p more than doubles it. Prompt-following degrades on very long multi-shot scripts."),
 'Seedance 1.5': ("Very good quality-per-dollar with audio (~$0.26 for a 720p 5s clip); solid all-rounder.",
                  "Token-based pricing is hard to predict; fewer control knobs than 2.x; no multi-shot."),
 'Seedance 1.0': ("Fast tier is genuinely cheap for 1080p; clean, stable motion for product and b-roll shots.",
                  "No audio, no reference mode, and superseded by 1.5/2.x on realism."),

 'LTX-2.5': ("Open-source synchronized audio+video in one pass; pro/fast tiers; best open alternative to Veo for talking scenes.",
             "Newer and less battle-tested; megapixel billing punishes long or high-res renders."),
 'LTX-2.3': ("Widest configuration surface on fal — 22B/quality/distilled/LoRA variants, audio, and per-megapixel billing that makes short clips very cheap.",
             "Endpoint sprawl is confusing; the base 2.3 tier starts at 1080p (no cheaper 720p tier); LoRA variants cost more per megapixel."),
 'LTX-2 19B': ("Cheap per-megapixel pricing, native audio, LoRA support and up to 481 frames — the best cost-per-frame in the quality tier.",
               "Megapixel billing means cost scales with resolution AND length; motion is less cinematic than Kling/Veo."),
 'LTX-Video (legacy)': ("Extremely fast and cheap; fully open weights; good for previews and iteration.",
                        "Visibly dated quality — soft textures, weak coherence past ~3s, no audio."),

 'Wan 2.7': ("Latest Wan: smoother motion, better scene fidelity and coherence, with a reference-to-video mode.",
             "New enough that community LoRA/tooling support lags 2.2; pricing sits above the 2.2 tiers."),
 'Wan 2.5/2.6': ("Strong all-round open-weight quality with audio support; the 2.6 flash tier is fast and cheap.",
                 "Preview-grade stability; documentation and parameter surface keep shifting between versions."),
 'Wan 2.2 A14B': ("The open-weights sweet spot — LoRA support, turbo tier, 480p/580p/720p control, huge community ecosystem.",
                  "No native audio, 81–161 frame ceiling (~5–10s at 16fps), and 16fps output needs interpolation for smooth playback."),
 'Wan 2.2 5B': ("Cheapest credible 720p generation on the platform (~$0.30/min via distill/fast-wan tiers); runs almost anywhere.",
                "5B capacity shows on complex motion and faces; 5s cap; no audio."),
 'Wan Pro': ("Premium 1080p at 30fps with excellent motion diversity for a Wan 2.1-era model.",
             "1080p-only (no cheap 720p tier), fixed 6s, expensive relative to Wan 2.2, no audio."),
 'Wan 2.1': ("Battle-tested open model with t2v/i2v/flf2v/effects endpoints and LoRA support; very cheap.",
             "Superseded quality; 480p/720p only; no audio."),
 'Krea-Wan': ("Krea's aesthetic tuning on Wan 14B gives a distinctly more stylish, less 'AI-looking' image for $0.025/s.",
              "Single t2v endpoint only; 16fps; no audio or image conditioning."),

 'Hailuo 2.3': ("Outstanding motion realism and character physics for the price; standard tier is one of the best value picks on fal.",
                "Fixed 6s/10s durations, no aspect-ratio control on most endpoints, no native audio."),
 'Hailuo 02': ("Best-in-class physical motion (the 'gymnast' benchmark model); very cheap standard tier at $0.045/s.",
               "768p standard / 1080p pro only, no aspect control, no audio, fixed durations."),
 'MiniMax H3': ("Frontier MiniMax model — 2K and 4K output, 5–15s, seven aspect ratios, LoRA and reference modes.",
                "Premium pricing at 2K/4K; 768p is the only cheap tier; ecosystem still young."),
 'MiniMax video-01': ("Director endpoint exposes explicit camera-movement commands; 'live' variant is tuned for illustration/anime motion.",
                      "Fixed 6s at 720p, no audio, and quality is a generation behind Hailuo 02/2.3."),

 'Pixverse V6': ("Newest Pixverse: best prompt adherence in the line, with transition mode included.",
                 "Sparse documentation; audio support unclear; Pixverse's stylized bias persists."),
 'Pixverse V5.6': ("Higher-fidelity tier with audio and transition support.",
                   "Noticeably pricier than V5.5 ($0.45 vs $0.20 per 5s at 720p) for a modest jump."),
 'Pixverse V5.5': ("Adds multi-clip mode and audio while staying at $0.20 per 5s 720p clip — excellent value.",
                   "Multi-clip and audio both add surcharges that the headline price hides."),
 'Pixverse V5': ("Very cheap ($2.40/min at 720p), five aspect ratios, effects and transition endpoints.",
                 "No audio, 5s/8s only, and a persistent over-saturated 'AI video' look."),
 'Pixverse V4.5': ("Broad endpoint family (t2v/i2v/effects/transition/fast) at low cost; good template effects library.",
                   "Superseded by V5+; no audio; motion artifacts on complex scenes."),
 'Pixverse V4': ("Cheap and fast with the full effects/transition surface.",
                 "Dated quality, no audio, weak text rendering."),
 'Pixverse V3.5': ("Lowest-cost Pixverse tier; fine for simple looping social clips.",
                   "Clearly obsolete; soft detail and unstable faces."),
 'Pixverse C1': ("Film-grade tier with native audio, up to 1080p and 15s, plus reference-to-video — the strongest Pixverse offering.",
                 "Priced well above the numbered Pixverse tiers; newer and less documented."),
 'Pixverse misc': ("Swap replaces people, objects or backgrounds inside an existing clip — a genuinely rare capability.",
                   "Editing tool, not a generator; quality depends heavily on the input video."),

 'Vidu Q3': ("Strong multi-reference consistency (mix mode) and 1–16s continuous duration control across four resolutions.",
             "The 2.2x multiplier for 720p/1080p makes it pricey (~$9.24/min); audio support is thin."),
 'Vidu Q2': ("Best-in-class subject reference fidelity for the money; pro and turbo tiers.",
             "Odd hybrid pricing (per-request + per-second) is hard to forecast; 720p tier is limited."),
 'Vidu Q1': ("Reliable 1080p at a flat $0.40 per 5s clip, with reference and start-end modes.",
             "Fixed 5s, no audio, and motion is stiffer than Kling/Hailuo."),
 'Vidu 1.x': ("Cheapest reference-to-video and start-end-to-video on the platform; template mode gives one-click trends.",
              "4s fixed, low resolution, visibly dated motion."),

 'Grok Imagine 1.5': ("Audio included at every tier, three resolutions with transparent per-second pricing, and reference-to-video support.",
                      "xAI content policy is idiosyncratic; 1080p only on t2v; quality trails Veo/Kling on complex scenes."),
 'Grok Imagine': ("Very cheap audio-included generation ($0.07/s at 720p); fast turnaround.",
                  "Lower fidelity than 1.5, limited duration and aspect control."),

 'Luma Ray 3.2': ("Cinematic look with seamless looping control and reference images to lock subject/style — the loop feature is nearly unique.",
                  "Premium pricing; smaller ecosystem; no native audio."),
 'Luma Ray 2': ("Genuinely natural, coherent camera motion — still one of the most 'filmed' looking models. Flash tier is cheap.",
                "No audio, fixed 5s, and detail resolution trails newer models."),

 'Pika 2.2': ("Pikaframes (2–5 keyframes with per-transition prompts) enables ~25s multi-beat sequences; Pikascenes composes multiple subjects.",
              "1080p costs 2.25x 720p; no audio; character consistency drifts across keyframes."),
 'Pika 2.1': ("Strong character control and cinematic camera moves for the price.",
              "Superseded by 2.2; 5s fixed; no audio."),
 'Pika 2 Turbo': ("Fastest Pika tier — good for rapid iteration.",
                  "Lowest quality in the Pika line; 5s; no audio."),

 'FLUX.3 Video': ("BFL's frontier video model with a full control surface: t2v, i2v, first-last-frame and keyframes-to-video, each with a cheap draft mode.",
                  "Draft mode is 720p-only; the quality tier is expensive at 1080p ($0.29/s); very new, little community knowledge."),
 'Gemini Omni Flash': ("Synchronized audio plus Gemini's real-world grounding and physics understanding — the best 'plausible world' model.",
                       "Google safety filtering is aggressive; limited duration and aspect control; reference mode is basic."),
 'Alibaba Happy Horse': ("1080p with synchronized native audio, 3–15s, five aspect ratios, and a reference-to-video mode — a very complete feature set.",
                         "Little independent evaluation available; v1.1 and v1.0 differences are undocumented."),
 'Bernini-R': ("ByteDance's unified generation + editing model — one endpoint for both, with reference support.",
               "Editing-oriented; documentation is minimal; not tuned for pure cinematic output."),

 'Hunyuan 1.5': ("Tencent's best open model — strong motion and detail at $0.045/s, with an image-to-video variant.",
                 "Only one resolution tier documented; no audio; smaller LoRA ecosystem than Wan."),
 'Hunyuan (legacy)': ("Open weights with excellent text-video alignment for its generation; strong motion diversity.",
                      "129-frame cap, no audio, slow, and superseded by Hunyuan 1.5."),
 'Kandinsky 5 Pro': ("Fast high-quality diffusion with a 1024p tier; genuinely open Russian-lab alternative.",
                     "No 720p tier (512p or 1024p only), so 720p work overpays; no audio; weak English prompt nuance."),
 'Kandinsky 5': ("Flat $0.05–$0.16 per clip regardless of resolution — extremely predictable cost. Distill tier is very fast.",
                 "Lower fidelity than Wan/LTX at the same price; no audio; 5s/10s only."),
 'LongCat': ("Purpose-built for long-form: 720p/30fps with a distilled tier at $0.01 per generated second — the cheapest long video on fal.",
             "Quality is clearly below frontier models; separate endpoints per resolution; no audio."),
 'Cosmos 3': ("NVIDIA omnimodal world model — video, audio and action commands from text/image/video/trajectory inputs. Unique for robotics and simulation.",
              "Aimed at world-modeling, not aesthetics; sparse documentation; niche."),
 'Cosmos Predict 2.5': ("Physically grounded world simulation from NVIDIA; deterministic fixed output makes it reproducible.",
                        "Fixed 1280x704 and 93 frames — no duration, resolution or aspect control at all; no audio."),
 'Moonvalley Marey': ("Trained exclusively on fully licensed data — the only clearly clean-rights model on the platform, which matters for commercial work.",
                      "By far the most expensive ($1.50 per 5s = $18/min); no audio; slower than everything else."),
 'Infinity-Star': ("8B spacetime autoregressive engine — roughly 10x faster than diffusion at 720p, for $0.07 per video.",
                   "Very short clips, minimal control surface, and quality well below diffusion peers."),
 'MAGI': ("Exceptional understanding of physical interaction and cinematic prompts for a distilled model.",
          "$0.32 per 4s is poor value now; 96-frame cap; inference-step surcharges stack quickly."),
 'Ovi': ("Unified audio+video generation in one pass at $0.20 per 5s clip — cheap synchronized sound.",
         "Fixed 5s and low resolution; audio quality is rough compared to Veo/LTX-2.5."),
 'Decart Lucy': ("Real-time class: 5-second i2v in under 5 seconds (>1x realtime) — the fastest i2v on fal.",
                 "Quality is traded for speed; 5s fixed; no audio or fine control."),
 'ByteDance Lynx': ("Very strong subject consistency from a single reference image.",
                    "Single endpoint, minimal controls, short output."),
 'FramePack': ("Autoregressive generation keeps memory flat, so it handles longer clips cheaply; flf2v variant supports end frames.",
               "Slow, 30fps-but-soft output, and drift accumulates over long generations."),
 'CogVideoX': ("Fully open 5B weights, easy to self-host, decent prompt following for its size.",
               "8fps output, 49-frame cap, obsolete quality."),
 'SVD': ("Historically important, extremely cheap, and fast; good for subtle image animation.",
         "25 frames at 6–10fps, no prompt control in the classic sense, no audio — effectively a motion-nudge tool."),
 'AnimateDiff': ("Cheap stylized/anime motion with a turbo tier; strong LoRA compatibility.",
                 "Very short, low resolution, flickery — a 2023-era pipeline."),
 'T2V-Turbo': ("Fast and cheap short clips for prototyping.",
               "Obsolete quality and resolution."),

 'HeyGen': ("Production-grade digital twins with lip-sync, backgrounds, captions and MP4/WebM output; avatar3/4/5 tiers plus video-agent endpoints.",
            "Requires avatar setup; costly at $0.10/s for avatar4; presenter-framing only."),
 'VEED': ("Fabric 1.0 turns a single photo into a talking presenter at $0.35/minute — the cheapest talking-head on the platform.",
          "Head-and-shoulders framing only; limited expressiveness; no scene generation."),
 'Mirage Avatar-X': ("Industry-leading identity preservation and expressivity, with up to 180s of speech — the longest avatar output here.",
                     "Voice reference constraints (10–180s) add setup friction; premium positioning."),
 'OmniHuman': ("Emotion and body motion correlate strongly with the audio, not just lips — the most lifelike audio-driven human model.",
               "Needs a good full-figure reference image; ~30s ceiling; no scene control."),
 'Argil': ("Avatar videos generated straight from text with a natural, non-uncanny feel.",
           "Closed avatar library; little control over framing or scene."),
 'fal AI-Avatar': ("Infinitalk and the multi-speaker endpoints handle two-person conversations — rare among avatar models.",
                   "$0.20/s for the multi endpoint is steep; faces drift on long takes."),
 'Sync Lipsync': ("Works on illustrations and animated frames, not just photoreal faces.",
                  "$0.13/s; single-speaker only; no body motion."),
 'Talking-head (legacy)': ("Nearly free (GPU-second billed) and instant; SadTalker/MuseTalk/LivePortrait are fine for quick previews.",
                           "Obvious artifacts, small motion range, and dated quality — not client-ready."),
 'Utility': ("Deterministic and nearly free — exactly what you want for stitching or interpolation.",
             "Not generative at all; no creative control."),
}

rows = json.load(open('final.json'))
missing = set()
for r in rows:
    f = r['family_key']
    if f in V:
        r['f_strong'], r['f_weak'] = V[f]
    else:
        missing.add(f)
        r['f_strong'] = r['f_weak'] = ''
json.dump(rows, open('final.json', 'w'), indent=1)
print('families covered:', len(V), '| uncovered:', sorted(missing))
print('rows without verdict:', sum(1 for r in rows if not r['f_strong']))
