"""Family verdicts for the image and audio atlases.

Same contract as the video atlas: sides describe capabilities, use-cases name
production scenarios, and the two must not repeat each other. Sources: fal
model pages/descriptions (Aug 2026) plus external research — Artificial
Analysis leaderboards, vendor documentation, and practitioner reviews.

Each entry: family -> (strong side, weak side, strong use-cases, weak use-cases)
"""

IMAGE = {
 'FLUX.2': ("BFL's frontier line: top-tier photorealism, texture and dense typography, up to 4MP output and 10 reference images, with per-megapixel pricing and draft tiers.",
            "Reference images bill separately (~$0.03/MP each), so multi-ref workflows get pricey; instruction-following and world knowledge trail Nano Banana Pro.",
            "Hero product shots, campaign key visuals, cinematic and painterly art direction, dense typographic posters.",
            "Fact-grounded infographics, many-reference identity work on a budget, conversational iterative editing."),
 'FLUX.1': ("The workhorse open family (dev/schnell): huge ecosystem, predictable quality, cheap and fast.",
            "Superseded by FLUX.2 on realism and text; weak hands/fine anatomy by 2026 standards.",
            "High-volume drafts, LoRA-based pipelines, self-hosted products already built on FLUX.1.",
            "Frontier-quality client work, accurate long text."),
 'FLUX 1.1 Pro': ("Strong aesthetics-per-dollar with ultra/raw modes at 4MP.",
                  "Closed weights; superseded by FLUX.2 Pro for most briefs.",
                  "Marketing stills, moodboards, quick premium drafts.",
                  "Editing workflows — it is generation-only."),
 'FLUX Pro': ("The original FLUX quality tier; stable and battle-tested.",
              "Two generations old now.",
              "Legacy pipelines pinned to its look.", "New projects."),
 'FLUX Kontext': ("In-context editing with plain-language instructions on FLUX quality; dev/pro/max tiers.",
                  "Single-image focus; complex multi-step edits drift; superseded by FLUX.2 edit modes.",
                  "One-shot object swaps, restyles, text replacement in existing images.",
                  "Multi-image composition, identity-across-scenes work."),
 'FLUX Krea': ("Krea's aesthetic finetune of FLUX — opinionated, less 'AI-looking' output.",
               "Narrower prompt range; the strong look is hard to steer away from.",
               "Fashion, lifestyle and design-forward social content.",
               "Neutral/documentary styles, precise brand-color control."),
 'FLUX LoRA': ("FLUX.1 with arbitrary community LoRAs — the largest style ecosystem anywhere.",
               "Quality rides on the LoRA; stacking them degrades coherence.",
               "Brand-style pipelines, character consistency via trained LoRAs, stylized volume work.",
               "Zero-setup one-offs — training or picking LoRAs is the workflow."),
 'FLUX ControlNet': ("Depth/canny-conditioned FLUX generation for layout-locked output.",
                     "Control fidelity below dedicated SDXL ControlNet stacks for some maps.",
                     "Product-in-layout shots, architecture from linework, pose-locked characters.",
                     "Freeform creative generation."),
 'Juggernaut FLUX': ("RunDiffusion's photoreal FLUX finetune — skin, lighting and lens realism above base.",
                     "Less flexible on stylized looks.",
                     "Photoreal portraits and lifestyle imagery.",
                     "Illustration, typography."),
 'Ideogram': ("Best-in-class text rendering and layout control (v4 adds JSON prompting, bounding boxes, palettes); open weights at the frontier of design.",
              "Photorealism and prompt reasoning trail closed leaders; busy scenes can look graphic-design-flat.",
              "Posters, packaging, ads, thumbnails, logos, any image where words must be readable.",
              "Cinematic photorealism, subtle photographic editing."),
 'Qwen Image Edit': ("The strongest open-weights instruction editor (20B): in-image text rewriting, multi-image edits, ControlNet built in.",
                     "Heavy model — slower and pricier than small editors; occasional over-editing.",
                     "Text correction inside images, e-commerce photo cleanup, batch instruction edits, LoRA-styled edits.",
                     "From-scratch generation (use Qwen Image or a t2i model)."),
 'Qwen Image': ("Alibaba's 20B generator with excellent bilingual (CJK+Latin) text rendering.",
                "Aesthetics trail FLUX.2/Seedream on western-style photography.",
                "Chinese-market creative, bilingual signage and packaging.",
                "Painterly art direction."),
 'fal Editing presets': ("One-call task presets (background swap, relight, restyle...) — zero prompt engineering.",
                         "Preset-shaped: no fine control; quality varies by task.",
                         "Quick production fixes in automated pipelines.",
                         "Anything needing art direction."),
 'fal Image Apps': ("Packaged consumer-style effects (headshots, avatars, filters) as single endpoints.",
                    "Novelty-grade output; opaque internals.",
                    "Fast feature prototypes, consumer app effects.",
                    "Brand-controlled imagery."),
 'Post-processing': ("Deterministic finishing utilities (grain, sharpen, color ops).",
                     "Not generative; narrow.",
                     "Pipeline finishing passes.", "Content creation."),
 'Preprocessors': ("ControlNet auxiliaries (depth, pose, edges) as endpoints.",
                   "Utility only.",
                   "Feeding control maps into generation pipelines.", "Standalone use."),
 'Z-Image': ("#1 open-source model on Artificial Analysis (early 2026): 6B, sub-second turbo, Apache-2.0, strong CJK+Latin typography, runs on 16GB VRAM.",
             "Small model limits complex composition and long-prompt fidelity.",
             "High-volume photoreal generation on a budget, self-hosted products, Chinese typography.",
             "Complex multi-subject scenes, heavy editing workflows."),
 'Bria FIBO': ("JSON-native structured prompting trained on licensed data — repeatable, parameter-locked generation for enterprises.",
               "Aesthetic ceiling below frontier consumer models.",
               "Regulated-industry creative, template-driven ad variants at scale.",
               "One-off artistic exploration."),
 'Bria': ("Fully licensed training data with indemnification; solid commercial-safe generation and editing.",
          "Quality a tier below the frontier; conservative outputs.",
          "Legal-sensitive enterprise work, stock-replacement imagery.",
          "Edgy or highly stylized creative."),
 'Recraft': ("True vector (SVG/EPS) generation plus design-aware raster with brand-style locking — art-directed, print-ready output.",
             "Photorealism is not the point; raster realism mid-tier.",
             "Logos, icons, brand systems, UI assets, print collateral.",
             "Photoreal scenes, people."),
 'Upscalers': ("Dedicated super-resolution (Topaz, Clarity, ESRGAN, SUPIR...) — real detail recovery at production scale.",
               "Can hallucinate texture; per-MP cost stacks on large prints.",
               "Print prep, archive restoration, AI-output upscaling.",
               "Content generation."),
 'SD/SDXL legacy': ("Free-tier compute pricing, LoRA/ControlNet ecosystems, fully understood behavior.",
                    "2023-era quality: anatomy, text and coherence all dated.",
                    "Hobby projects, education, existing SDXL pipelines.",
                    "Anything competing on quality in 2026."),
 'SDXL ControlNet': ("Mature, precise structural control (canny/depth/union) on SDXL.",
                     "SDXL base quality underneath.",
                     "Layout-exact compositing where structure beats fidelity.",
                     "Final-quality output."),
 'Seedream': ("ByteDance's unified gen+edit frontier model — 4K output, strong prompt adherence, cheap at ~$0.03/image; v4.5 tops several arenas.",
              "Aesthetic bias toward clean commercial looks; weaker community tooling.",
              "E-commerce and product imagery at volume, brand campaigns, 4K masters on a budget.",
              "Fine-art direction, western editorial styles."),
 'GPT Image': ("OpenAI's instruction-following and world knowledge in image form; conversational editing strength.",
               "Token pricing is opaque and can spike; slow; strict content policy.",
               "Knowledge-grounded illustrations, iterative what-if editing, UI mockups with sensible text.",
               "High-volume fixed-cost pipelines, uncensored creative range."),
 'Nano Banana': ("Gemini-native editing with world knowledge at a very low price; fast.",
                 "1K fixed output; complex compositions simplify.",
                 "Quick edits, meme-speed iteration, knowledge-aware tweaks.",
                 "4K masters, print."),
 'Nano Banana Pro': ("Gemini 3 Pro image tier: walls of accurate text, up to 14 reference images, 5-person consistency, real-world grounding via search.",
                     "Priciest Google tier; Google content filters.",
                     "Fact-accurate infographics, multi-reference brand/character work, text-heavy creative.",
                     "Budget bulk generation."),
 'Gemini Image': ("Conversational multimodal editing on Gemini models — iterate in plain language.",
                  "Fixed sizes; token pricing; filters.",
                  "Chat-style creative iteration, mixed text+image workflows.",
                  "Deterministic batch pipelines."),
 'Grok Imagine Image': ("Fast, cheap stills from the Grok stack with editing modes.",
                        "720p-class output; X-ecosystem moderation quirks.",
                        "Meme-speed social content, drafts for Grok video.",
                        "Print, 4K, brand-safety-critical work."),
 'Luma Photon': ("Photon/Photon Flash: cinematic-photographic look with strong reference/style conditioning.",
                 "Smaller ecosystem; text rendering weak.",
                 "Film-look stills, style-locked series.",
                 "Typography, infographics."),
 'Sana': ("NVIDIA's tiny ultra-fast model (4K in ~1s class); efficient at scale.",
          "Detail and adherence trail big models.",
          "Realtime previews, latency-sensitive apps.",
          "Final-quality output."),
 'HiDream': ("Strong open aesthetic model family (I1/O1) with editing variants; arena-competitive.",
             "Less tooling than FLUX ecosystem.",
             "High-quality open-weights generation, stylized portraits.",
             "Text-heavy design."),
 'Hunyuan Image': ("Tencent's bilingual frontier model, strong at CJK text and dense scenes.",
                   "Western aesthetic styles trail; ecosystem thin outside China.",
                   "Chinese-market campaigns, bilingual design.",
                   "English-idiom creative."),
 'Ernie Image': ("Baidu's generator with solid Chinese-language understanding.",
                 "Little independent evaluation; conservative outputs.",
                 "Chinese-market content.", "Everything else — better-known peers exist."),
 'Microsoft MAI': ("Microsoft's first in-house image family; clean instruction following.",
                   "Young — few reviews, unclear niche vs incumbents.",
                   "Azure-adjacent experimentation.", "Production commitments."),
 'ImagineArt': ("Aggregator-tuned generation tiers focused on consumer aesthetics.",
                "Derivative capability; opaque versioning.",
                "Consumer-app style output.", "Precise control work."),
 'Fooocus': ("SDXL wrapped with automatic prompt expansion — good output with zero prompt skill.",
             "SDXL-era ceiling; opinionated defaults.",
             "Beginners, quick concept art.", "Controlled production."),
 'Kling Image': ("Kling's image line incl. Kolors virtual try-on.",
                 "Image side is a sideshow to their video models.",
                 "Try-on demos, Kling-ecosystem stills.", "General generation."),
 'Kolors': ("Kwai's photoreal SDXL-class model, strong on faces.",
            "Dated vs 2026 frontier.",
            "Photoreal portraits on a budget.", "Text, complex scenes."),
 'Playground': ("Aesthetic-tuned generation (v2.5) that once led human-preference boards.",
                "Frozen in 2024; no editing.",
                "Stylized social graphics.", "Current-gen briefs."),
 'Krea': ("Krea's realtime/enhance stack — fast iterative generation.",
          "Quality tier below frontier.",
          "Live ideation, enhancement passes.", "Final masters."),
 'Reve': ("Design-aware generation with strong adherence (Halfmoon lineage).",
          "Small ecosystem.",
          "Design comps, art direction exploration.", "Volume pipelines."),
 'Patina': ("Style-preserving photo editing.",
            "Narrow.", "Photo restyles keeping subject fidelity.", "Generation."),
 'Phota': ("Consumer photo enhancement suite.",
           "Utility-grade.", "Selfie/photo cleanup features.", "Creative work."),
 'Vision/captioning': ("Vision-language utilities (captioning, VQA).",
                       "Not generators.", "Alt-text, dataset labeling, prompt mining.", "Image creation."),
 'Florence vision': ("Microsoft Florence-2 vision tasks (caption, detect, OCR) as endpoints.",
                     "Analysis only.", "Captioning and OCR in pipelines.", "Generation."),
 'SAM segmentation': ("Segment-Anything (v1/2) masks as a service.",
                      "Masks only.", "Auto-masking for edits, dataset prep.", "Generation."),
 'Background removal': ("Specialist cutout models (BiRefNet, RMBG, Bria) — clean edges at scale.",
                        "Single task.", "E-commerce cutouts, batch compositing prep.", "Anything else."),
 'Object removal': ("Inpainting-based erasers (Finegrain) tuned for clean removals.",
                    "Complex occlusion still fails sometimes.",
                    "Photo cleanup, retail image sanitization.", "Creative generation."),
 'Restoration': ("Deblur/denoise/colorize/face-restore specialists (NAFNet, CodeFormer, DDColor...).",
                 "Per-task models, no unified control.",
                 "Archive restoration, UGC cleanup.", "Net-new imagery."),
 'Face/identity': ("Identity-preserving generation (PuLID, InstantID, PhotoMaker) and portrait animation.",
                   "Identity drift under big pose/style shifts.",
                   "Personalized avatars, consistent-character content.", "Non-portrait work."),
 'Virtual try-on': ("Garment transfer onto model photos (CatVTON, Leffa, Fashn).",
                    "Struggles with complex garments/poses; body diversity varies.",
                    "E-commerce apparel try-on at scale.", "Editorial fashion art."),
 'Relighting': ("IC-Light-class photometric relighting with light-source control.",
                "Can flatten materials.",
                "Product-photo relight, composite harmonization.", "General editing."),
 'Stylize minis': ("One-trick style converters (Ghibli, cartoon, pixel).",
                   "Single look each.", "Novelty features, campaign gimmicks.", "Brand systems."),
 'SD community minis': ("Community checkpoints (Pony, DreamShaper) with devoted niches.",
                        "Dated bases.", "Niche community aesthetics.", "Commercial work."),
 'Open T2I minis': ("Research-notable open models (PixArt, Lumina, OmniGen, CogView4...).",
                    "Each superseded by newer opens.",
                    "Research baselines, curiosity.", "Production."),
 'Labs T2I misc': ("Assorted lab models (SenseNova, Ovis, Boogu...).",
                   "Thin documentation and evals.",
                   "Evaluation and benchmarking.", "Committed pipelines."),
 'Edit specialists misc': ("Single-purpose research editors (ChronoEdit, DreamOmni, StepX...) — some beat generalists on their niche.",
                          "Fragmented; per-model quirks.",
                          "Specific edit tasks after testing the exact model.", "General-purpose editing."),
 'Image utilities': ("Deterministic helpers (resize, SVG-trace, watermark, interpolation).",
                     "Not generative.", "Pipeline glue.", "Creation."),
 'E-commerce tools': ("Product-photo staging (Pixelcut).",
                      "Template-bound.", "Marketplace listing images.", "Brand campaigns."),
 '3D/world minis': ("Image-to-3D/world experiments (Hunyuan World, Hi3D).",
                    "Early tech.", "3D asset prototyping.", "Production 3D."),
 'OmniGen': ("Unified any-task image model (generate+edit+compose) in one checkpoint.",
             "Master of none vs specialists.",
             "Research on unified interfaces.", "Peak-quality tasks."),
 'Autoregressive misc': ("AR-based generators (Infinity, Emu) — different failure modes than diffusion.",
                         "Behind diffusion on fidelity.",
                         "Research comparisons.", "Production."),
 'Lumina': ("Open DiT research model.", "Research-grade.", "Baselines.", "Production."),
 'Janus': ("DeepSeek's unified understanding+generation research model.",
           "Small, dated.", "Research.", "Production."),
 'GLM Image': ("Zhipu's image model with strong Chinese comprehension.",
               "Thin evals.", "Chinese-market tests.", "General work."),
 'Boogu': ("Niche lab generator.", "Unknown quantity.", "Evaluation.", "Production."),
 'LongCat Image': ("Meituan's image line alongside LongCat video.",
                   "Young, thin docs.", "Ecosystem experiments.", "Committed pipelines."),
 'MiniMax Image': ("MiniMax's image side of the Hailuo stack.",
                   "Video is their focus.", "Hailuo-ecosystem stills.", "Standalone image work."),
 'Vidu Image': ("Vidu's reference-consistent image generation feeding its video stack.",
                "Niche outside that pipeline.",
                "Character sheets for Vidu video workflows.", "General generation."),
 'Wan Image': ("Wan-family image endpoints — strong open aesthetics, LoRA-friendly.",
               "Image side less famous than video.",
               "Stills matching Wan video looks, open pipelines.", "Typography."),
 'Kandinsky Image': ("Sber's open family with distinctive palette.",
                     "Behind frontier.", "Russian-market, research.", "Frontier briefs."),
 'ByteDance Image misc': ("Bernini-R image mode — renderer-grade editing.",
                          "Renderer-only limits.", "Style transfer experiments.", "Human-centric gen."),
 'NVIDIA Cosmos Image': ("Physics-aware frames from the Cosmos world model.",
                         "Not aesthetic.", "Robotics/AV data.", "Creative work."),
 'GPT Image ': None,  # guard against trailing-space dupes
}
IMAGE = {k: v for k, v in IMAGE.items() if v}

AUDIO = {
 'Stable Audio 3': None,  # resolved below to 'Stable Audio'
 'Stable Audio': ("Open-weights latent-diffusion family (small/medium) trained on fully licensed Warner/Universal data; t2a, a2a, inpaint/outpaint; up to ~6 min output; LoRA support.",
                  "Deliberately instrumental-only — no vocals; small tiers trade fidelity for speed.",
                  "Royalty-clean instrumental beds, SFX design, editing/extending existing audio, self-hosted pipelines.",
                  "Songs with vocals, lyric-driven tracks."),
 'MiniMax Speech': ("Top-of-leaderboard TTS (2.6/2.8): 10-second voice cloning that speaks 40+ languages, emotional nuance, HD and Turbo tiers, voice design from text descriptions.",
                    "Cloning consent controls are on you; per-character billing adds up at audiobook scale.",
                    "Voice agents, multilingual dubs from one clone, character voices for games/apps, expressive narration.",
                    "Free/self-hosted deployments (closed model), music."),
 'MiniMax Music': ("Full-song generation with vocals from lyrics + style prompts.",
                   "Less structural control than dedicated DAW workflows; artifacting on dense mixes.",
                   "Demo songs, jingles, lyric-to-song prototypes.",
                   "Instrumental precision work, stems for mixing."),
 'Kokoro': ("#1-per-parameter TTS: 82M params, Apache-2.0, near-instant CPU inference, 54 preset voices across 9 language lines on fal.",
            "No voice cloning at all; expressiveness ceiling below big models.",
            "High-volume low-cost narration, edge/on-device speech, multilingual UI voices.",
            "Brand voices, emotional acting, cloned identities."),
 'ElevenLabs': ("The polish benchmark: v3 expressiveness, robust multilingual TTS, dubbing, isolation and voice-changer endpoints on fal.",
                "Premium pricing; v3 not realtime; cloning gated by plan.",
                "Client-facing narration, audiobooks, dubbing pipelines, voice cleanup.",
                "Budget bulk TTS (open models are 10x cheaper), self-hosting."),
 'ElevenLabs SFX': ("Text-to-SFX with production-grade punch.",
                    "Short one-shots; pricing per generation.",
                    "Foley and UI sounds on demand.", "Long ambient beds."),
 'ACE-Step': ("Open-source music foundation model: 4 min of music in ~20s on an A100, lyric-aligned composition, voice-clone/remix/lyric2vocal controls; 1.5 tops open benchmarks.",
              "Vocal realism still trails Suno-class closed models; you supply the lyrics.",
              "Full-length structured songs with vocals, remix/cover experiments, local music pipelines.",
              "Radio-ready vocal polish, hands-off lyric writing."),
 'Qwen TTS': ("Alibaba's TTS line incl. ultra-cheap voice-clone tiers (~$0.0008/min).",
              "Mandarin-first quality; English prosody flatter.",
              "Massive-scale cheap narration, CJK voice products.",
              "Premium English brand voices."),
 'Mirelo SFX': ("Video-aware SFX generation (sound matched to video content).",
                "Niche; young model.",
                "Auto-foley for generated video.", "Music, speech."),
 'Chatterbox': ("Resemble's open TTS that beat ElevenLabs in blind tests (65% preference): zero-shot cloning from ~5s, emotion exaggeration control, HD tier.",
                "English-centric; long-form stability needs chunking.",
                "Cloned narration at open-source cost, expressive character reads, s2s voice conversion.",
                "40-language dubbing, CPU-only deployments."),
 'VibeVoice': ("Microsoft's long-form multi-speaker TTS (up to 90 min, 4 speakers) — podcast-grade.",
               "0.5B tier is flat; big tier is slow.",
               "Podcast/dialogue synthesis, audiobook chapters in one pass.",
               "Single short lines (overkill), cloning."),
 'Maya TTS': ("Emotion-tagged expressive TTS.",
              "Young model, small voice set.",
              "Character dialogue with acted emotion.", "Neutral corporate reads."),
 'Google Lyria': ("DeepMind-grade instrumental music (Lyria 2/3) with strong musicality per clip.",
                  "30s-class clips; no vocals; Google filters.",
                  "Score-quality beds and stingers.", "Full songs, vocal tracks."),
 'Sonilo': ("Music generation focused on loops/beds.",
            "Small player.", "Background loops.", "Vocal music."),
 'LTX Audio': ("Audio tracks generated for/with LTX video.",
               "Pricing copy on fal still shows video terms; audio-alone value unclear.",
               "Soundtracks inside LTX video workflows.", "Standalone audio."),
 'Kling Audio': ("TTS + voice creation feeding Kling's video/avatar stack.",
                 "Basic vs dedicated TTS.",
                 "Voices for Kling avatar videos.", "Standalone narration."),
 'Dia TTS': ("Nari Labs' dialogue-native TTS — two-speaker scripts with laughs/coughs/interruptions.",
             "English only, no cloning, quirky stability.",
             "Podcast-style two-hander scenes.", "Corporate narration."),
 'SAM Audio': ("Segment-anything-for-audio: isolate any source by text prompt.",
               "Separation only.", "Dialogue/music/FX stem extraction.", "Generation."),
 'PersonaPlex': ("Persona-conditioned conversational voice.",
                 "Early.", "Voice-agent prototypes.", "Broadcast polish."),
 'Tada TTS': ("Lightweight TTS.", "Thin docs.", "Cheap experiments.", "Production."),
 'Audio utilities': ("Deterministic audio ops (ffmpeg, merge, probe).",
                     "Not generative.", "Pipeline glue.", "Creation."),
 'CassetteAI Music': ("Fast loop/track generation at $0.01-0.03 per clip.",
                      "Loop-grade quality.", "Bulk background loops.", "Featured music."),
 'CassetteAI SFX': ("Cheap one-shot SFX.", "Basic.", "Game jam assets.", "Film-grade foley."),
 'ByteDance Audio': ("Seed-Audio 1.0 — ByteDance's general audio model.",
                     "Young.", "Ecosystem experiments.", "Committed pipelines."),
 'Gemini TTS': ("Gemini-native TTS with conversational control.",
                "Token pricing; preview-grade.",
                "Gemini-stack apps.", "Fixed-cost bulk narration."),
 'F5-TTS': ("Open zero-shot cloning TTS with strong similarity.",
            "Needs clean reference; English/Chinese focus.",
            "Self-hosted cloning research.", "Polished production."),
 'MMAudio': ("Video-synchronized audio generation (open).",
             "Rough fidelity.", "Auto-foley research for video.", "Music."),
 'DiffRhythm': ("Open full-song diffusion (lyrics→song, fast).",
                "Vocal artifacts.", "Song prototypes locally.", "Release-ready tracks."),
 'Sesame CSM': ("Open conversational speech model with context-aware prosody.",
                "Research-grade stability.", "Voice-agent research.", "Production narration."),
 'Zonos': ("Open TTS with cloning + emotion control (v1/v2).",
           "Quality below Chatterbox on blind tests.",
           "Self-hosted cloning on a budget.", "Premium reads."),
 'Inworld TTS': ("Game-NPC-oriented TTS with low latency.",
                 "Niche voice set.", "Game dialogue at runtime.", "Long narration."),
 'xAI TTS': ("Grok-stack TTS.", "Young; moved out of beta with price hike.",
             "X-ecosystem apps.", "Standalone TTS value."),
 'IndexTTS': ("Bilibili's open TTS strong on Chinese prosody.",
              "CJK-first.", "Chinese narration.", "English brand voices."),
 'Orpheus TTS': ("Open Llama-based TTS with emotive tags.",
                 "English-centric.", "Expressive open-source reads.", "Multilingual dubs."),
 'Async TTS': ("Pro TTS tier from Async.", "Thin public evals.",
               "Testing.", "Committed pipelines."),
 'Demucs': ("The standard open stem-separation model.",
            "Separation only.", "Karaoke/remix stems, mix analysis.", "Generation."),
 'Audio understanding': ("Audio QA/analysis endpoint.",
                         "Not generative.", "Content tagging.", "Creation."),
 'DeepFilterNet': ("Real-time speech denoising.",
                   "Denoise only.", "Podcast/call cleanup.", "Generation."),
}
AUDIO = {k: v for k, v in AUDIO.items() if v}
